# Numpy Beginning


In [ ]:
import numpy as np

## Creation of Array

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
 #List
 a=[1,2,3,4.333]
 print(a)
 print(type(a))

[1, 2, 3, 4.333]
<class 'list'>


In [ ]:
#List contain multilpe datatypes
b=[1,2,3,4.5,"Mitesh"]
print(b)
print(type(b))


[1, 2, 3, 4.5, 'Mitesh']
<class 'list'>


In [ ]:
# copnversion of list into array
arr1=np.array(b)
arr1
#All datatypes converted to string


array(['1', '2', '3', '4.5', 'Mitesh'], dtype='<U32')

In [ ]:
#what if i give float and int
arr2=np.array(a)
arr2
#All datatypes coverted to float

array([1.   , 2.   , 3.   , 4.333])

In [ ]:
#vector
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [ ]:
#matrices
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array generation functions

 ## **np.arange()**

In [ ]:
arr = np.arange(1,10) #last element not included
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(1,11,2) #difference of 2
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.arange(1,11,3) #difference of 3
arr

array([ 1,  4,  7, 10])

In [ ]:
arr = np.arange(10,1,-2) #reverse
arr

array([10,  8,  6,  4,  2])

##  **np.zeros()  && np.ones()**

1.   List item
2.   List item



In [ ]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((2,2))
arr

array([[0., 0.],
       [0., 0.]])

In [ ]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [ ]:
arr=np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

In [ ]:
arr=np.linspace(1,5,3) #gives  3 numbers with equal difference between 1--5
arr

array([1., 3., 5.])

In [ ]:
 arr=np.linspace(10,100,10)
 arr

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## **Random Generation functions**

In [ ]:
np.random.rand(10)  #generates random 10 numbers from 0--1

array([0.39045124, 0.0280968 , 0.26063789, 0.4745272 , 0.64811353,
       0.40297881, 0.6973836 , 0.47949252, 0.75944177, 0.36273536])

In [ ]:
np.random.randn(10)

array([-0.02788323, -1.78617569,  0.62701948,  0.18453111, -1.42554612,
        0.62340201,  0.49965298, -1.01648296, -1.20068736,  0.16279217])

In [ ]:
np.random.randint(10) #generates single random number from 0--9

1

In [ ]:
np.random.randint(10,20) #generates single random number from 10--19

15

In [ ]:
np.random.randint(10,20,10) #generates  10 random numbers from 10--19

array([16, 18, 15, 14, 14, 12, 18, 14, 17, 13])

## **Array Attributes**

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape #A tuple representing the size of each dimension.

(3, 3)

In [ ]:
arr.size #Total number of elements in the array

9

In [ ]:
arr.dtype #Data type of the array elements.

dtype('int64')

In [ ]:
arr.ndim #Returns the number of dimensions (axes) of the array.

2

In [ ]:
arr.itemsize #Size (in bytes) of each element Output: 8 (if int64)

8

In [ ]:
arr.nbytes # Total bytes consumed by the array (itemsize * size).

72

In [ ]:
arr.T # Returns the transposed array (swap rows and columns).

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## **Array Methods**

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=0) #column wise sum

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

## **Reshaping and resizing**

In [ ]:
arr=np.arange(1,36)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35])

In [ ]:
arr.reshape(7,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])