In [ ]:
import numpy as np

# **Numpy Indexing and slicing of vectors**

In [ ]:
arr=np.arange(11,31)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [ ]:
#indexing
arr[6]

np.int64(17)

In [ ]:
#Slicing  same as list
arr[2:6]

array([13, 14, 15, 16])

In [ ]:
arr[:6]

array([11, 12, 13, 14, 15, 16])

In [ ]:
arr[6:]

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [ ]:
arr[2::2]

array([13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
arr[3:10:2]

array([14, 16, 18, 20])

# **Numpy indexing and Slicing of Matrix**

In [ ]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[4] # Row

array([21, 22, 23, 24, 25])

In [ ]:
arr[0,0]

np.int64(1)

In [ ]:
arr[0:2,1:3] #slicingg firs mention row then column

array([[2, 3],
       [7, 8]])

In [ ]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
#another method to obtain above cell result
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,2] # accessing column

array([ 3,  8, 13, 18, 23, 28])

# **Boolean Indexing**

In [ ]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index=arr % 2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# **Array Operations**

## **Arithmetic operation**

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
print(a1)
print(a2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [ ]:
a1+a2 # Both array sizes should be same to carry operations

array([ 7,  9, 11, 13, 15])

In [ ]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1-a2

array([-5, -5, -5, -5, -5])

In [ ]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1//a2

array([0, 0, 0, 0, 0])

In [ ]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

# **BroadCasting**

In [ ]:
l = [10,20,30,40]
arr1=np.array(l)
arr1

array([10, 20, 30, 40])

In [ ]:
arr1+10 # if we want to add 10 in list we have to run for loop thats why we convert them into array

array([20, 30, 40, 50])

In [ ]:
arr2=np.arange(1,26).reshape(5,5)
print(arr2)
arr2+10

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

### **Deep and shallow copy**

In [ ]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice=arr[:5]
slice

array([1, 2, 3, 4, 5])

In [ ]:
slice =slice+17
slice

array([18, 19, 20, 21, 22])

In [ ]:
arr  #this was the concept of shallow copy even if we sliced some portion of array and changes it original array is same

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#Deep copy
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b=a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b[1]=100
b

array([  1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [ ]:
a # changes made in b are also reflected in a

array([  1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [ ]:
#But if we wnat to make shallow copy of a we can simply do
b=a.copy()
print("This shallow copy of a b :",b)
b=b+10
print("b after modification :",b)
print("a:",a)

This shallow copy of a b : [  1 100   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
b after modification : [ 11 110  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28
  29  30]
a: [  1 100   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


## ***Matrix operations***

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
A@B #multiplication in Matrix

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(A,B) #sot product same multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
A.T

array([[1, 3],
       [2, 4]])

### **Advance Array Manipulation**

Stacking Array

In [ ]:
 # we can stack vectors but not matrices

In [ ]:
 a=np.array([1,2,3,4,5])
 b=np.array([6,7,8,9,10])

In [ ]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Splitting Arrays

In [ ]:
f=np.arange(16).reshape(4,4)
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(f,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.hsplit(f,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
np.vsplit(f,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.vsplit(f,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]